# Generated by Django 4.0.6 on 2022-09-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
