# Generated by Django 4.0.6 on 2022-08-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
