# Generated by Django 4.0.6 on 2022-08-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lta', '0002_user_bio_user_image_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='media/images/'),
        ),
    ]
