# Generated by Django 4.0.6 on 2022-09-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lta', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Link',
        ),
    ]
